#!/bin/bash
# VITAEGIS - Manual Deployment Steps
# Since CLI authentication has network restrictions, use the Vercel Dashboard

echo "🚀 VITAEGIS Deployment to vitaegis.com"
echo "======================================"
echo ""
echo "Due to CLI authentication restrictions, please deploy via Vercel Dashboard:"
echo ""
echo "📋 Step 1: Import Your Repository"
echo "   → Go to: https://vercel.com/new"
echo "   → Sign in with your GitHub account"
echo "   → Click 'Import Git Repository'"
echo "   → Search for: vitae/vitaegis"
echo "   → Click 'Import'"
echo ""
echo "⚙️  Step 2: Configure (Auto-detected)"
echo "   ✓ Framework: Next.js"
echo "   ✓ Root Directory: ./"
echo "   ✓ Build Command: npm run build"
echo "   ✓ Output Directory: .next"
echo "   → Click 'Deploy'"
echo ""
echo "🌐 Step 3: Add Custom Domain"
echo "   → After deployment, go to Project Settings → Domains"
echo "   → Add: vitaegis.com"
echo "   → Add: www.vitaegis.com"
echo ""
echo "📡 Step 4: Configure DNS (at your domain registrar)"
echo ""
echo "   A Record:"
echo "   └─ Type: A"
echo "   └─ Name: @"
echo "   └─ Value: 76.76.21.21"
echo ""
echo "   CNAME Record:"
echo "   └─ Type: CNAME"
echo "   └─ Name: www"
echo "   └─ Value: cname.vercel-dns.com"
echo ""
echo "⏱️  Wait 5-30 minutes for DNS propagation"
echo ""
echo "✅ Your site will be live at:"
echo "   → https://vitaegis.com"
echo "   → https://www.vitaegis.com"
echo ""
echo "🔄 Auto-Deployment:"
echo "   Every 'git push' will automatically deploy to vitaegis.com!"
echo ""
echo "📊 Direct Link to Import:"
echo "   https://vercel.com/new/git"
echo ""
