/* Generated from the KeyCrate audio analysis of the official "Sunrise at the Gorge" release. */

export interface SetTrack {
  pos: number;
  title: string;
  start: number;
  end: number;
  camelot: string;
  key: string;
  bpm: number | null;
  beatless: boolean;
}
export interface SetTransition {
  n: number;
  at: number;
  start: number;
  end: number;
  frm: string;
  to: string;
  keys: string;
  move: string;
  tempo: string;
  cut: boolean;
  secs: number;
  half: boolean;
  pct: number;
  tags: string[];
  steps: string[];
}

export const DURATION = 3639;

export const TRACKS: SetTrack[] = [
  {
    pos: 1,
    title: 'Tweak Sauce (intro)',
    start: 0,
    end: 38,
    camelot: '9B',
    key: 'G',
    bpm: 120,
    beatless: true,
  },
  {
    pos: 2,
    title: 'Bullet Holes And Such',
    start: 38,
    end: 330,
    camelot: '8A',
    key: 'Am',
    bpm: 120,
    beatless: false,
  },
  {
    pos: 3,
    title: 'Fallow VIP',
    start: 330,
    end: 485,
    camelot: '9A',
    key: 'Em',
    bpm: 86,
    beatless: false,
  },
  {
    pos: 4,
    title: 'Algae Bloom in Seven VIP',
    start: 485,
    end: 888,
    camelot: '7A',
    key: 'Dm',
    bpm: 108,
    beatless: false,
  },
  {
    pos: 5,
    title: 'Ambergris VIP',
    start: 888,
    end: 1024,
    camelot: '7A',
    key: 'Dm',
    bpm: 80,
    beatless: false,
  },
  {
    pos: 6,
    title: 'Out Of Here VIP',
    start: 1024,
    end: 1378,
    camelot: '5A',
    key: 'Cm',
    bpm: 86,
    beatless: false,
  },
  {
    pos: 7,
    title: 'Apex of the Vortex VIP',
    start: 1378,
    end: 1680,
    camelot: '7A',
    key: 'Dm',
    bpm: 175,
    beatless: false,
  },
  {
    pos: 8,
    title: 'Loosies VIP',
    start: 1680,
    end: 1843,
    camelot: '9B',
    key: 'G',
    bpm: 129,
    beatless: true,
  },
  {
    pos: 9,
    title: 'Pillow Roulette VIP 3.0',
    start: 1843,
    end: 2057,
    camelot: '12B',
    key: 'E',
    bpm: 96,
    beatless: false,
  },
  {
    pos: 10,
    title: 'Flares at Dawn VIP',
    start: 2057,
    end: 2309,
    camelot: '2B',
    key: 'F#',
    bpm: 152,
    beatless: false,
  },
  {
    pos: 11,
    title: 'Air Biscuits VIP',
    start: 2309,
    end: 2520,
    camelot: '1A',
    key: 'Abm',
    bpm: 89,
    beatless: false,
  },
  {
    pos: 12,
    title: 'ID',
    start: 2520,
    end: 2634,
    camelot: '1A',
    key: 'Abm',
    bpm: 116,
    beatless: true,
  },
  {
    pos: 13,
    title: 'ID?',
    start: 2634,
    end: 2735,
    camelot: '10A',
    key: 'Bm',
    bpm: 74,
    beatless: false,
  },
  {
    pos: 14,
    title: 'Tethers VIP',
    start: 2735,
    end: 3048,
    camelot: '9A',
    key: 'Em',
    bpm: 148,
    beatless: true,
  },
  {
    pos: 15,
    title: 'Ever Decreasing Circles VIP',
    start: 3048,
    end: 3280,
    camelot: '5B',
    key: 'Eb',
    bpm: 70,
    beatless: false,
  },
  {
    pos: 16,
    title: 'Virga VIP',
    start: 3280,
    end: 3639,
    camelot: '2B',
    key: 'F#',
    bpm: 136,
    beatless: false,
  },
];

export const TRANSITIONS: SetTransition[] = [
  {
    n: 1,
    at: 38,
    start: 35,
    end: 39,
    frm: 'Tweak Sauce (intro)',
    to: 'Bullet Holes And Such',
    keys: '9B → 8A',
    move: 'diagonal',
    tempo: '120.2 → 120.2 BPM (+0%)',
    cut: true,
    secs: 4,
    half: false,
    pct: 0,
    tags: ['CUT', 'BASS SWAP', 'ECHO 1 beat', 'NO SYNC'],
    steps: [
      'Around 0:35, let the outgoing track finish its phrase.',
      'Throw the echo at the beat length shown, then pull the fader so only the repeats remain.',
      'Drop the next track on the downbeat (same tempo family, so sync is fine).',
    ],
  },
  {
    n: 2,
    at: 330,
    start: 315,
    end: 336,
    frm: 'Bullet Holes And Such',
    to: 'Fallow VIP',
    keys: '8A → 9A',
    move: 'perfect 5th (±1)',
    tempo: '120.2 → 86.2 BPM (-28%)',
    cut: false,
    secs: 21,
    half: false,
    pct: -28,
    tags: ['BLEND 21s', 'REVERB'],
    steps: [
      'At 5:15, start the next track unsynced (tempos 28% apart; the overlap is atmospheric, not beatmatched), fader down and low EQ cut.',
      'Bring the fader up across about 21 s.',
      'By 5:36 the outgoing track is gone.',
    ],
  },
  {
    n: 3,
    at: 485,
    start: 479,
    end: 493,
    frm: 'Fallow VIP',
    to: 'Algae Bloom in Seven VIP',
    keys: '9A → 7A',
    move: 'energy step (±2)',
    tempo: '86.2 → 107.8 BPM (+25%)',
    cut: false,
    secs: 14,
    half: false,
    pct: 25,
    tags: ['BLEND 14s', 'HPF in'],
    steps: [
      'At 7:59, start the next track unsynced (tempos 25% apart; the overlap is atmospheric, not beatmatched), fader down and low EQ cut.',
      'Start it with the high-pass filter on and open the filter slowly across the blend.',
      'Bring the fader up across about 14 s.',
      'By 8:13 the outgoing track is gone.',
    ],
  },
  {
    n: 4,
    at: 888,
    start: 923,
    end: 927,
    frm: 'Algae Bloom in Seven VIP',
    to: 'Ambergris VIP',
    keys: '7A → 7A',
    move: 'same key',
    tempo: '107.8 → 80.0 BPM (-26%)',
    cut: true,
    secs: 3,
    half: false,
    pct: -26,
    tags: ['CUT', 'HPF in', 'ECHO ½ beat'],
    steps: [
      'Around 15:23, let the outgoing track finish its phrase.',
      'Throw the echo at the beat length shown, then pull the fader so only the repeats remain.',
      "Drop the next track on the downbeat. The tempo jumps -26%: don't sync or try to beatmatch.",
    ],
  },
  {
    n: 5,
    at: 1024,
    start: 1020,
    end: 1032,
    frm: 'Ambergris VIP',
    to: 'Out Of Here VIP',
    keys: '7A → 5A',
    move: 'energy step (±2)',
    tempo: '80.0 → 86.0 BPM (+8%)',
    cut: false,
    secs: 12,
    half: false,
    pct: 8,
    tags: ['BLEND 12s', 'ECHO ¼ beat'],
    steps: [
      'At 17:00, start the next track, synced, fader down and low EQ cut.',
      'Bring the fader up across about 12 s.',
      'Echo the outgoing track as it leaves.',
      'By 17:12 the outgoing track is gone.',
    ],
  },
  {
    n: 6,
    at: 1378,
    start: 1388,
    end: 1396,
    frm: 'Out Of Here VIP',
    to: 'Apex of the Vortex VIP',
    keys: '5A → 7A',
    move: 'energy step (±2)',
    tempo: '86.0 → 175.0 BPM (+103%, half/double-time)',
    cut: false,
    secs: 8,
    half: true,
    pct: 103,
    tags: ['BLEND 8s', 'ECHO 1 beat', '½×/2× TEMPO'],
    steps: [
      'At 23:08, start the next track, synced, fader down and low EQ cut.',
      'Bring the fader up across about 8 s.',
      'Echo the outgoing track as it leaves.',
      'By 23:16 the outgoing track is gone.',
    ],
  },
  {
    n: 7,
    at: 1680,
    start: 1677,
    end: 1685,
    frm: 'Apex of the Vortex VIP',
    to: 'Loosies VIP',
    keys: '7A → 9B',
    move: 'clash',
    tempo: '175.0 → 129.2 BPM (-26%)',
    cut: false,
    secs: 7,
    half: false,
    pct: -26,
    tags: ['BLEND 7s', 'BASS SWAP', 'TEMPO RAMP', 'NO SYNC'],
    steps: [
      'At 27:57, start the next track (beatless passage, no sync needed), fader down and low EQ cut.',
      'Bring the fader up across about 7 s.',
      'Swap the bass at the midpoint: outgoing low EQ down, incoming low EQ up.',
      'By 28:05 the outgoing track is gone.',
      'Before the change the outgoing section moves toward the new tempo. On your decks, ride the pitch slider over 8–16 bars, or skip it and cut.',
    ],
  },
  {
    n: 8,
    at: 1843,
    start: 1801,
    end: 1805,
    frm: 'Loosies VIP',
    to: 'Pillow Roulette VIP 3.0',
    keys: '9B → 12B',
    move: 'minor third (±3)',
    tempo: '129.2 → 95.8 BPM (-26%)',
    cut: true,
    secs: 4,
    half: false,
    pct: -26,
    tags: ['CUT', 'NO SYNC'],
    steps: [
      'Around 30:01, let the outgoing track finish its phrase.',
      'Pull the fader (or cut the low EQ) on the last downbeat.',
      "Drop the next track on the downbeat. The tempo jumps -26%: don't sync or try to beatmatch.",
    ],
  },
  {
    n: 9,
    at: 2057,
    start: 2056,
    end: 2076,
    frm: 'Pillow Roulette VIP 3.0',
    to: 'Flares at Dawn VIP',
    keys: '12B → 2B',
    move: 'energy step (±2)',
    tempo: '95.8 → 152.0 BPM (+59%)',
    cut: false,
    secs: 20,
    half: false,
    pct: 59,
    tags: ['BLEND 20s'],
    steps: [
      'At 34:16, start the next track unsynced (tempos 59% apart; the overlap is atmospheric, not beatmatched), fader down and low EQ cut.',
      'Bring the fader up across about 20 s.',
      'By 34:36 the outgoing track is gone.',
    ],
  },
  {
    n: 10,
    at: 2309,
    start: 2307,
    end: 2311,
    frm: 'Flares at Dawn VIP',
    to: 'Air Biscuits VIP',
    keys: '2B → 1A',
    move: 'diagonal',
    tempo: '152.0 → 89.0 BPM (-41%)',
    cut: true,
    secs: 4,
    half: false,
    pct: -41,
    tags: ['CUT'],
    steps: [
      'Around 38:26, let the outgoing track finish its phrase.',
      'Pull the fader (or cut the low EQ) on the last downbeat.',
      "Drop the next track on the downbeat. The tempo jumps -41%: don't sync or try to beatmatch.",
    ],
  },
  {
    n: 11,
    at: 2520,
    start: 2513,
    end: 2523,
    frm: 'Air Biscuits VIP',
    to: 'ID',
    keys: '1A → 1A',
    move: 'same key',
    tempo: '89.0 → 116.0 BPM (+30%)',
    cut: false,
    secs: 10,
    half: false,
    pct: 30,
    tags: ['BLEND 10s', 'BASS SWAP', 'TEMPO RAMP', 'NO SYNC'],
    steps: [
      'At 41:53, start the next track (beatless passage, no sync needed), fader down and low EQ cut.',
      'Bring the fader up across about 10 s.',
      'Swap the bass at the midpoint: outgoing low EQ down, incoming low EQ up.',
      'By 42:03 the outgoing track is gone.',
      'Before the change the outgoing section moves toward the new tempo. On your decks, ride the pitch slider over 8–16 bars, or skip it and cut.',
    ],
  },
  {
    n: 12,
    at: 2634,
    start: 2631,
    end: 2637,
    frm: 'ID',
    to: 'ID?',
    keys: '1A → 10A',
    move: 'minor third (±3)',
    tempo: '116.0 → 73.8 BPM (-36%)',
    cut: true,
    secs: 6,
    half: false,
    pct: -36,
    tags: ['CUT', 'NO SYNC'],
    steps: [
      'Around 43:51, let the outgoing track finish its phrase.',
      'Pull the fader (or cut the low EQ) on the last downbeat.',
      "Drop the next track on the downbeat. The tempo jumps -36%: don't sync or try to beatmatch.",
    ],
  },
  {
    n: 13,
    at: 2735,
    start: 2702,
    end: 2751,
    frm: 'ID?',
    to: 'Tethers VIP',
    keys: '10A → 9A',
    move: 'perfect 5th (±1)',
    tempo: '73.8 → 147.8 BPM (+100%, half/double-time)',
    cut: false,
    secs: 49,
    half: true,
    pct: 100,
    tags: ['BLEND 49s', 'ECHO 1 beat', 'NO SYNC', '½×/2× TEMPO'],
    steps: [
      'At 45:02, start the next track (beatless passage, no sync needed), fader down and low EQ cut.',
      'Bring the fader up across about 49 s.',
      'Echo the outgoing track as it leaves.',
      'By 45:51 the outgoing track is gone.',
    ],
  },
  {
    n: 14,
    at: 3048,
    start: 3073,
    end: 3083,
    frm: 'Tethers VIP',
    to: 'Ever Decreasing Circles VIP',
    keys: '9A → 5B',
    move: 'clash',
    tempo: '147.8 → 69.8 BPM (-53%, half/double-time)',
    cut: false,
    secs: 10,
    half: true,
    pct: -53,
    tags: ['BLEND 10s', 'HPF in', 'TEMPO RAMP', 'NO SYNC', '½×/2× TEMPO'],
    steps: [
      'At 51:13, start the next track (beatless passage, no sync needed), fader down and low EQ cut.',
      'Start it with the high-pass filter on and open the filter slowly across the blend.',
      'Bring the fader up across about 10 s.',
      'By 51:23 the outgoing track is gone.',
      'Before the change the outgoing section moves toward the new tempo. On your decks, ride the pitch slider over 8–16 bars, or skip it and cut.',
    ],
  },
  {
    n: 15,
    at: 3280,
    start: 3267,
    end: 3272,
    frm: 'Ever Decreasing Circles VIP',
    to: 'Virga VIP',
    keys: '5B → 2B',
    move: 'minor third (±3)',
    tempo: '69.8 → 136.0 BPM (+95%, half/double-time)',
    cut: true,
    secs: 5,
    half: true,
    pct: 95,
    tags: ['CUT', 'HPF out', 'ECHO ¼ beat', 'RISER', 'TEMPO RAMP', '½×/2× TEMPO'],
    steps: [
      'Around 54:27, let the outgoing track finish its phrase.',
      'Throw the echo at the beat length shown, then pull the fader so only the repeats remain.',
      "Drop the next track on the downbeat. It's a half-time/double-time switch: don't beatmatch, the new groove takes over.",
      'Before the change the outgoing section moves toward the new tempo. On your decks, ride the pitch slider over 8–16 bars, or skip it and cut.',
      'A noise/riser sweep (Beat FX "Noise" or Sound Color "Noise") for the last 4–8 bars before the change.',
    ],
  },
];
